# Generated by Django 4.2.6 on 2023-11-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewedItem',
            new_name='Reviewed_Item',
        ),
    ]
