# Generated by Django 4.2.6 on 2023-11-03 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_author_author_list'),
        ('user_profile', '0002_alter_profile_student_contact_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_rename_revieweditem_reviewed_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewed_item',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reviewed_item',
            name='object_id',
        ),
        migrations.AddField(
            model_name='reviewed_item',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewed_item',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewed_item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
