# Generated by Django 4.2.6 on 2023-10-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(default='default_book_image.jpg', upload_to='book_images/cover')),
                ('overview_image', models.ImageField(default='default_book_overview_image.jpg', upload_to='book_images/overview')),
                ('table_of_contents_image', models.ImageField(default='default_book_table_of_contents_image.jpg', upload_to='book_images/table_of_contents')),
                ('isbn_number', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date_published', models.DateField(null=True)),
                ('inventory', models.IntegerField()),
                ('rack_number', models.CharField(max_length=255)),
                ('rack_level_number', models.CharField(max_length=255)),
            ],
        ),
    ]
