# Generated by Django 5.0.2 on 2024-02-09 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('author_image', models.ImageField(default='default_profile_image.jpg', upload_to='author_images')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(default='default_book_image.jpg', upload_to='book_images/cover')),
                ('overview_image', models.ImageField(default='default_book_overview_image.jpg', upload_to='book_images/overview')),
                ('table_of_contents_image', models.ImageField(default='default_book_table_of_contents_image.jpg', upload_to='book_images/table_of_contents')),
                ('isbn_number', models.CharField(max_length=255)),
                ('date_published', models.DateField(null=True)),
                ('inventory', models.IntegerField()),
                ('rack_number', models.CharField(max_length=255)),
                ('rack_level_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Author_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.book')),
            ],
        ),
    ]
