# Generated by Django 5.0.2 on 2024-02-09 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('Request', 'Request'), ('Borrowed', 'Borrowed'), ('Pending', 'Pending'), ('Returned', 'Returned'), ('Approved', 'Approved')], default='Request', max_length=15)),
                ('request_created', models.DateTimeField(auto_now_add=True)),
                ('pick_up_date', models.DateField(null=True)),
                ('return_due_date', models.DateField(null=True)),
                ('returned_date', models.DateField(null=True)),
                ('pending_days', models.IntegerField(null=True)),
                ('fine', models.IntegerField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.book')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_id', to=settings.AUTH_USER_MODEL)),
                ('staff_approve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_approve_id', to=settings.AUTH_USER_MODEL)),
                ('staff_borrow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_borrow_id', to=settings.AUTH_USER_MODEL)),
                ('staff_return', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_return_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
