# Generated by Django 4.2.6 on 2023-10-27 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('Borrowed', 'Borrowed'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Request', 'Request')], default='Request', max_length=15)),
                ('request_created', models.DateTimeField(auto_now_add=True)),
                ('pick_up_date', models.DateField()),
                ('return_due_date', models.DateField()),
                ('return_date', models.DateField()),
                ('pending_days', models.IntegerField()),
                ('fine', models.IntegerField()),
                ('staff_approve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_approve_id', to=settings.AUTH_USER_MODEL)),
                ('staff_borrow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_borrow_id', to=settings.AUTH_USER_MODEL)),
                ('staff_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_return_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
