# Generated by Django 4.2.6 on 2023-10-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_author_author_list'),
        ('borrow_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_book',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='book.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow_book',
            name='request_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Borrowed', 'Borrowed'), ('Request', 'Request'), ('Pending', 'Pending')], default='Request', max_length=15),
        ),
    ]
