# Generated by Django 4.2.6 on 2023-10-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0003_borrow_book_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='request_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Borrowed', 'Borrowed'), ('Request', 'Request')], default='Request', max_length=15),
        ),
    ]
