# Generated by Django 4.2.6 on 2023-10-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0004_alter_borrow_book_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='fine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='borrow_book',
            name='pending_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='borrow_book',
            name='pick_up_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='borrow_book',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Request', 'Request'), ('Borrowed', 'Borrowed'), ('Approved', 'Approved')], default='Request', max_length=15),
        ),
        migrations.AlterField(
            model_name='borrow_book',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='borrow_book',
            name='return_due_date',
            field=models.DateField(null=True),
        ),
    ]
