# Generated by Django 4.2.6 on 2023-11-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0007_rename_return_date_borrow_book_returned_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='request_status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Approved', 'Approved'), ('Borrowed', 'Borrowed'), ('Request', 'Request'), ('Pending', 'Pending')], default='Request', max_length=15),
        ),
    ]
