# Generated by Django 4.2.6 on 2023-11-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0009_alter_borrow_book_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='request_status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Borrowed', 'Borrowed'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Request', 'Request')], default='Request', max_length=15),
        ),
    ]
