# Generated by Django 4.2.7 on 2023-11-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0013_alter_borrow_book_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='request_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Request', 'Request'), ('Borrowed', 'Borrowed'), ('Returned', 'Returned')], default='Request', max_length=15),
        ),
    ]
