# Generated by Django 4.2.7 on 2023-11-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0014_alter_borrow_book_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='request_status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Borrowed', 'Borrowed'), ('Approved', 'Approved'), ('Request', 'Request'), ('Pending', 'Pending')], default='Request', max_length=15),
        ),
    ]
