# Generated by Django 5.0.1 on 2024-02-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0016_alter_borrow_book_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='request_status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Request', 'Request'), ('Returned', 'Returned'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Request', max_length=15),
        ),
    ]
