# Generated by Django 5.0.2 on 2024-02-09 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default_profile_image.jpg', upload_to='thesis_author_images')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_published', models.DateField(null=True)),
                ('image', models.ImageField(default='default_thesis_image.jpg', upload_to='thesis_images')),
                ('file', models.FileField(default='testing.pdf', upload_to='thesis_files')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Author_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_id', to='thesis.author')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thesis_id', to='thesis.thesis')),
            ],
        ),
    ]
