# Generated by Django 4.2.6 on 2023-10-25 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('thesis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='course.course'),
            preserve_default=False,
        ),
    ]
