# Generated by Django 4.2.6 on 2023-10-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_thesis_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='image',
            field=models.ImageField(default='default_thesis_image.jpg', upload_to='thesis_images'),
        ),
    ]
