# Generated by Django 4.2.7 on 2023-12-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_thesis_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='file',
            field=models.FileField(default='testing.pdf', upload_to='thesis_files'),
        ),
    ]
