# Generated by Django 5.0.2 on 2024-02-09 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_profile_image.jpg', upload_to='profile_images')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'O')], default='O', max_length=20)),
                ('student_number', models.CharField(max_length=100, null=True, unique=True)),
                ('student_contact_no', models.CharField(max_length=15, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.barangay')),
                ('city_municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.city_municipality')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='course.course')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.province')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
